#!/usr/bin/env bash

_yay() {
    args=("$@")

    # When yay has other flags passed in, it will exit if no other
    # arguments are provided. Therefore, add the default arguments
    # when no arguments are passed by the user.
    if [[ -z "${args[*]}" ]]; then
        args="-Syu"
    fi

    # Uses unshare as sudo to enable running pacman without sudo
    # Run pacman through unshare to enable use without sudo. Additionally, point various flags
    # to the virtual environment instead of the root directory
    PATH="${PATH#*:}" yay \
        --sudo /usr/bin/unshare \
        --sudoflags "--map-root-user" \
        --cachedir "${_PACMAN_VENV}/var/cache/pacman/pkg" \
        --hookdir "${_PACMAN_VENV}/etc/pacman.d/hooks" \
        --root "${_PACMAN_VENV}" \
        "${args[@]}"
}

_yay "$@"
