blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/jdholtz/pacman-venv/discussions/new/choose
    about: Use Github Discussions to ask questions and/or open discussion topics.
