#!/usr/bin/env bash
set -e

DEFAULT_DESTINATION="pacman-venv"
VERSION="v0.0"

CURR_DIR="$(dirname "${0}")"
ACTIVATION_DIRECTORY="${CURR_DIR}/activation"
SHIMS_DIRECTORY="${CURR_DIR}/shims"

# Import message helper functions
source "${CURR_DIR}/output/messages.sh"

version() {
    echo "Pacman Virtual Environment ${VERSION}"
}

usage() {
    version
    echo
    echo "Usage:"
    echo "    pacman-venv [options]        Create a virtual environment with the default name"
    echo "    pacman-venv [options] [dest] Create a virtual environment with the specified name"
    echo
    echo "Options:"
    echo "    -h, --help    Display this help and exit"
    echo "    -v, --version Display information version and exit"
}

# Install pacman and its dependencies. The entire base system is not
# needed in the virtual environment as that will install packages not
# necessary for the virtual environment.
install_pacman() {
    local root_dir="${1}"
    sudo pacman --root "${root_dir}" -Sy pacman --noconfirm
}

add_activation_script() {
    local destination="${1}"
    sudo cp "${ACTIVATION_DIRECTORY}/pacman-venv-activate.bash" "${destination}/bin/pacman-venv-activate"
}

# Add the necessary package manager executables to pass the --root argument to pacman
add_shims() {
    local destination="${1}"
    cp "${SHIMS_DIRECTORY}/pacman" "${destination}/.pacman-venv-pacman"
    cp "${SHIMS_DIRECTORY}/yay" "${destination}/.pacman-venv-yay"
}

# Add the .gitignore file so the virtual environment doesn't show up in git repositories
add_gitignore() {
    local destination="${1}"
    printf "# Created automatically by pacman-venv\n*\n" > "${destination}/.gitignore"
}

create() {
    local destination="${1}"
    local full_dest="${PWD}/${destination}"
    info "Creating pacman virtual environment in ${destination}"

    # Make the virtual environment directory and pacman
    # directory for pacman to install databases in.
    mkdir -p "${full_dest}/var/lib/pacman"

    info "Installing base environment"

    install_pacman "${full_dest}"

    add_activation_script "${full_dest}"
    add_shims "${full_dest}"
    add_gitignore "${full_dest}"

    info "Successfully created pacman virtual environment at ${destination}"
}

destination="${DEFAULT_DESTINATION}"

# Parse flags
while [[ ! "$#" == 0 ]]; do
    case "$1" in
        --help | -h)
            usage
            exit
            ;;
        --version | -v)
            version
            exit
            ;;
        -*)
            error "Invalid argument '${1}'"
            usage
            exit
            ;;
        *)
            destination="${1}"
            ;;
    esac
    shift
done

# Ensure destination is valid
if [[ -d "${PWD}/${destination}" ]] || [[ -f "${PWD}/${destination}" ]]; then
    error "Destination '${destination}' already exists!"
    exit 1
fi

create "${destination}"
