#!/usr/bin/env bash
set -e

DEFAULT_DESTINATION="pacman-venv"

CURR_DIR="$(dirname "${0}")"
ACTIVATION_DIRECTORY="${CURR_DIR}/activation"
SHIMS_DIRECTORY="${CURR_DIR}/shims"

# Import message helper functions
source "${CURR_DIR}/output/messages.sh"

create() {
    destination="${1}"
    full_dest="${PWD}/${destination}"
    info "Creating pacman virtual environment in ${destination}"

    # Make the pacman directory for pacman to install databases in
    mkdir -p "${full_dest}/var/lib/pacman"

    info "Installing base environment"

    # Install pacman and its dependencies. The entire base system is not needed as
    # that will install packages not necessary for the virtual environment.
    sudo pacman --root "${full_dest}" -Sy pacman --noconfirm

    # Add the activation script
    sudo cp "${ACTIVATION_DIRECTORY}/pacman-venv-activate.bash" "${full_dest}/bin/pacman-venv-activate"

    # Add the necessary package manager executables to pass the --root argument to pacman
    cp "${SHIMS_DIRECTORY}/pacman" "${full_dest}/.pacman-venv-pacman"
    cp "${SHIMS_DIRECTORY}/yay" "${full_dest}/.pacman-venv-yay"

    # Add the .gitignore file so the virtual environment doesn't show up in git repositories
    printf "# Created automatically by pacman-venv\n*\n" > "${full_dest}/.gitignore"

    info "Successfully created pacman virtual environment at ${destination}"
}

destination="${DEFAULT_DESTINATION}"
[[ "${1}" ]] && destination="${1}"

if [[ -d "${PWD}/${destination}" ]] || [[ -f "${PWD}/${destination}" ]]; then
    error "Destination '${destination}' already exists!"
    exit 1
fi

create "${destination}"
